"""Generate demo Excel inventory file."""

from pathlib import Path

import pandas as pd

DEMO_DIR = Path(__file__).parent


def generate_inventory():
    """Generate a sample inventory Excel file."""
    data = {
        "SKU": [f"SKU-{i:04d}" for i in range(1, 51)],
        "Product Name": [
            "Wireless Mouse",
            "USB-C Hub",
            "Laptop Stand",
            "Webcam HD",
            "Keyboard Mech",
            "Monitor Arm",
            "Desk Lamp",
            "Cable Kit",
            "Headset Pro",
            "Mouse Pad XL",
            "USB Drive 64GB",
            "HDMI Cable",
            "Power Strip",
            "Surge Protector",
            "Docking Station",
            "Phone Stand",
            "Screen Cleaner",
            "Wrist Rest",
            "Footrest",
            "Whiteboard",
            "Marker Set",
            "Sticky Notes",
            "Binder Clips",
            "Pen Set",
            "Notebook",
            "File Folders",
            "Label Maker",
            "Tape Dispenser",
            "Scissors Pro",
            "Stapler Heavy",
            "Paper Shredder",
            "Calculator",
            "Desk Organizer",
            "Bookend",
            "Clock Digital",
            "Fan USB",
            "Heater Mini",
            "Air Purifier",
            "Plant Pot",
            "Coaster Set",
            "Mug Warmer",
            "Water Bottle",
            "Snack Box",
            "First Aid Kit",
            "Hand Sanitizer",
            "Tissue Box",
            "Umbrella",
            "Tote Bag",
            "Badge Holder",
            "Lanyard",
        ],
        "Category": (["Electronics"] * 15 + ["Office Supplies"] * 15 + ["Furniture"] * 10 + ["Wellness"] * 10),
        "Unit Price": [
            24.99,
            34.99,
            49.99,
            59.99,
            89.99,
            39.99,
            29.99,
            18.99,
            79.99,
            14.99,
            9.99,
            7.99,
            19.99,
            24.99,
            149.99,
            12.99,
            8.99,
            19.99,
            49.99,
            39.99,
            14.99,
            4.99,
            3.99,
            9.99,
            6.99,
            8.99,
            29.99,
            5.99,
            12.99,
            14.99,
            89.99,
            12.99,
            24.99,
            14.99,
            19.99,
            14.99,
            34.99,
            79.99,
            9.99,
            12.99,
            19.99,
            14.99,
            24.99,
            29.99,
            4.99,
            3.99,
            14.99,
            9.99,
            4.99,
            2.99,
        ],
        "Quantity": [
            150,
            200,
            75,
            100,
            50,
            120,
            180,
            300,
            80,
            250,
            400,
            350,
            200,
            175,
            30,
            225,
            500,
            150,
            60,
            40,
            300,
            600,
            800,
            400,
            350,
            250,
            100,
            450,
            200,
            175,
            20,
            300,
            125,
            150,
            100,
            200,
            80,
            25,
            300,
            200,
            100,
            175,
            50,
            75,
            500,
            400,
            100,
            150,
            300,
            500,
        ],
        "Reorder Level": [
            50,
            75,
            25,
            30,
            20,
            40,
            60,
            100,
            25,
            80,
            150,
            120,
            70,
            60,
            10,
            75,
            200,
            50,
            20,
            15,
            100,
            200,
            300,
            150,
            120,
            80,
            30,
            150,
            70,
            60,
            5,
            100,
            40,
            50,
            30,
            70,
            25,
            8,
            100,
            70,
            30,
            60,
            15,
            25,
            200,
            150,
            30,
            50,
            100,
            200,
        ],
        "In Stock": [True] * 45 + [False] * 5,
    }

    df = pd.DataFrame(data)
    output_path = DEMO_DIR / "inventory.xlsx"
    df.to_excel(output_path, index=False)
    print(f"Generated {output_path} with {len(df)} rows")
    return df


if __name__ == "__main__":
    generate_inventory()
